(defun solve ()
  (interactive)
  (->> (split-string (buffer-substring-no-properties (point-min) (point-max)) "\n\n")
       (-map (lambda (x) (-filter (lambda (s) (not (string-empty-p s))) (split-string x "\n"))))
       (-map  (lambda (x) (-sum (-map #'string-to-number x))))
       (-sort #'>)
       (-first-item)
       (message "Answer: %d")))

(defun solve2 ()
  (interactive)
  (->> (split-string (buffer-substring-no-properties (point-min) (point-max)) "\n\n")
       (-map (lambda (x) (-filter (lambda (s) (not (string-empty-p s))) (split-string x "\n"))))
       (-map  (lambda (x) (-sum (-map #'string-to-number x))))
       (-sort #'>)
       (-take 3)
       (-sum)
       (message "Answer: %d")))
