(defun solve ()
  (interactive)
  (->> (split-string (buffer-substring-no-properties (point-min) (point-max)) "\n\n")
       (--map (--filter (not (string-empty-p it)) (split-string it "\n")))
       (--map (-sum (-map #'string-to-number it)))
       (-sort #'>)
       (-first-item)
       (message "Answer: %d")))

(defun solve2 ()
  (interactive)
  (->> (split-string (buffer-substring-no-properties (point-min) (point-max)) "\n\n")
       (--map (--filter (not (string-empty-p it)) (split-string it "\n")))
       (--map (-sum (-map #'string-to-number it)))
       (-sort #'>)
       (-take 3)
       (-sum)
       (message "Answer: %d")))
