(defun read-line ()
  (split-string (buffer-substring-no-properties (point-min) (point-max)) "\n\n" t " "))

(defun solve ()
  (interactive)
  (->> (read-line)
       (--map (split-string it "\n" t " "))
       (--map (-sum (-map #'string-to-number it)))
       (-sort #'>)
       (-first-item)
       (message "Solution 1: %d")))

(defun solve2 ()
  (interactive)
  (->> (read-line)
       (--map (split-string it "\n" t " "))
       (--map (-sum (-map #'string-to-number it)))
       (-sort #'>)
       (-take 3)
       (-sum)
       (message "Solution 2: %d")))
